//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppBorrarhehe.EmployeeWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeWS.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name PunchCardResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PunchCard", ReplyAction="*")]
        WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse PunchCard(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PunchCard", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse> PunchCardAsync(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest request);
        
        // CODEGEN: Generating message contract since element name PunchCard2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PunchCard2", ReplyAction="*")]
        WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response PunchCard2(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PunchCard2", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response> PunchCard2Async(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request request);
        
        // CODEGEN: Generating message contract since element name ListEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListEmployees", ReplyAction="*")]
        WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse ListEmployees(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse> ListEmployeesAsync(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse HelloWorld(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse> HelloWorldAsync(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PunchCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PunchCard", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequestBody Body;
        
        public PunchCardRequest() {
        }
        
        public PunchCardRequest(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PunchCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public PunchCardRequestBody() {
        }
        
        public PunchCardRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PunchCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PunchCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponseBody Body;
        
        public PunchCardResponse() {
        }
        
        public PunchCardResponse(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PunchCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PunchCardResult;
        
        public PunchCardResponseBody() {
        }
        
        public PunchCardResponseBody(string PunchCardResult) {
            this.PunchCardResult = PunchCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PunchCard2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PunchCard2", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2RequestBody Body;
        
        public PunchCard2Request() {
        }
        
        public PunchCard2Request(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PunchCard2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime timeStamp;
        
        public PunchCard2RequestBody() {
        }
        
        public PunchCard2RequestBody(int id, System.DateTime timeStamp) {
            this.id = id;
            this.timeStamp = timeStamp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PunchCard2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PunchCard2Response", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2ResponseBody Body;
        
        public PunchCard2Response() {
        }
        
        public PunchCard2Response(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PunchCard2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PunchCard2Result;
        
        public PunchCard2ResponseBody() {
        }
        
        public PunchCard2ResponseBody(string PunchCard2Result) {
            this.PunchCard2Result = PunchCard2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEmployees", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequestBody Body;
        
        public ListEmployeesRequest() {
        }
        
        public ListEmployeesRequest(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListEmployeesRequestBody {
        
        public ListEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponseBody Body;
        
        public ListEmployeesResponse() {
        }
        
        public ListEmployeesResponse(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.Worker[] ListEmployeesResult;
        
        public ListEmployeesResponseBody() {
        }
        
        public ListEmployeesResponseBody(WindowsFormsAppBorrarhehe.EmployeeWS.Worker[] ListEmployeesResult) {
            this.ListEmployeesResult = ListEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap>, WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.PunchCard(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest request) {
            return base.Channel.PunchCard(request);
        }
        
        public string PunchCard(int id) {
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequestBody();
            inValue.Body.id = id;
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse retVal = ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).PunchCard(inValue);
            return retVal.Body.PunchCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse> WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.PunchCardAsync(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest request) {
            return base.Channel.PunchCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardResponse> PunchCardAsync(int id) {
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCardRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).PunchCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.PunchCard2(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request request) {
            return base.Channel.PunchCard2(request);
        }
        
        public string PunchCard2(int id, System.DateTime timeStamp) {
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2RequestBody();
            inValue.Body.id = id;
            inValue.Body.timeStamp = timeStamp;
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response retVal = ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).PunchCard2(inValue);
            return retVal.Body.PunchCard2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response> WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.PunchCard2Async(WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request request) {
            return base.Channel.PunchCard2Async(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Response> PunchCard2Async(int id, System.DateTime timeStamp) {
            WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2Request();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.PunchCard2RequestBody();
            inValue.Body.id = id;
            inValue.Body.timeStamp = timeStamp;
            return ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).PunchCard2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.ListEmployees(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest request) {
            return base.Channel.ListEmployees(request);
        }
        
        public WindowsFormsAppBorrarhehe.EmployeeWS.Worker[] ListEmployees() {
            WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequestBody();
            WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse retVal = ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).ListEmployees(inValue);
            return retVal.Body.ListEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse> WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.ListEmployeesAsync(WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest request) {
            return base.Channel.ListEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesResponse> ListEmployeesAsync() {
            WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.ListEmployeesRequestBody();
            return ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).ListEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.HelloWorld(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequestBody();
            WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse retVal = ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse> WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap.HelloWorldAsync(WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest inValue = new WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequest();
            inValue.Body = new WindowsFormsAppBorrarhehe.EmployeeWS.HelloWorldRequestBody();
            return ((WindowsFormsAppBorrarhehe.EmployeeWS.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}
